 # Tomcat
server:
    port: 9023
    servlet:
        context-path: /caipiao-api
    # undertow 配置
    undertow:
        # HTTP post内容的最大大小。当值为-1时，默认值为大小是无限的
        max-http-post-size: -1
        # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
        # 每块buffer的空间大小,越小的空间被利用越充分
        buffer-size: 512
        # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
        io-threads: 16
        # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
        worker-threads: 386
        # 是否分配的直接内存
        direct-buffers: true
debug: false

spring:
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    mvc:
        throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false


#mybatis
mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    #实体扫描，多个package用逗号或者分号分隔
    type-aliases-package: com.caipiao.modules.*.entity.**
    typeEnumsPackage: com.caipiao.modules.*.entity.**
    type-handlers-package: com.caipiao.common.handler
    global-config:
        #数据库相关配置
        db-config:
            #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
            id-type: AUTO
            logic-delete-value: -1
            logic-not-delete-value: 0
        banner: false
    #原生配置
    configuration:
        default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
        map-underscore-to-camel-case: true
        cache-enabled: true
        call-setters-on-nulls: true
        jdbc-type-for-null: 'null'
    aes:
        key: FX42F0797B035B6280E4FEF93BE20POD
renren:
    # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
    jwt:
        # 加密秘钥
        secret: patrol@Login(Auth}*^31)&yun6%f3q2 # 登录校验的密钥
        pubKeyPath: rsa.pub # 公钥地址
        priKeyPath: rsa.pri # 私钥地址
        maxAge: 600
qiniu:
    type: 1
    domain: http://cartoon.333.cn/
    prefix: mc
    accessKey: VJoQ-np333heTVtXP5ZkZ8n9BHLLHQX
    secretKey: LOGyzom333ff7bVXj5SSBRCH4ERZTvDd
    bucketName: cartoon2022
rainbow:
    encrypt-iv: h6zue1kx70qc0d5h
    encrypt-key: dss0uxmagg6drrda
    enable: true
